import "dotenv/config"; //this is what import the dotenv package and it allow us to load environment variables from a .env file into our application and it will look for a .env file in the root directory of our project and it will load the variables defined in that file into the process.env object which we can then access in our application code and it will help us to keep sensitive information such as database connection strings, API keys, and other configuration settings out of our source code and it will also allow us to easily manage different configurations for different environments such as development, testing, and production by using different .env files for each environment and it will also help us to avoid hardcoding sensitive information in our source code which can be a security risk if our code is ever exposed or leaked
import { defineConfig, env } from "@prisma/config"; //this is what import the PrismaClient class from the @prisma/client package and it allow us to create an instance of the PrismaClient which we can then use to interact with our database and perform CRUD operations on our data and it will also allow us to manage the connection to the database and ensure that it is properly closed when we are done with it and it will also help us to manage the connection pool and ensure that we are not exceeding the maximum number of connections allowed by the database server and it will also help us to manage transactions and ensure that they are properly committed or rolled back in case of any errors that may occur during the transaction process and it will also help us to manage migrations and ensure that our database schema is up to date with our application code and it will also help us to manage seeding and ensure that our database is populated with initial data for testing or development purposes and it will also help us to manage logging and

export default  defineConfig ({
  schema: "./prisma/schema.prisma", //this is what specify the path to our Prisma schema file which is where we define our data models and the database connection settings and it will be used by the PrismaClient to generate the necessary code to interact with our database and perform CRUD operations on our data and it will also be used to manage migrations and ensure that our database schema is up to date with our application code and it will also be used to manage seeding and ensure that our database is populated with initial data for testing or development purposes and it will also be used to manage logging and ensure that we are logging any errors or important events that may occur during our application runtime for debugging or monitoring purposes
  migrations: {
    path: "prisma/migrations" //this is what specify the path to our Prisma migrations directory which is where we store our database migration files and it will be used by the PrismaClient to manage our database schema and ensure that it is up to date with our application code and it will also be used to manage seeding and ensure that our database is populated with initial data for testing or development purposes and it will also be used to manage logging and ensure that we are logging any errors or important events that may occur during our application runtime for debugging or monitoring purposes

  },
  datasource: {
    url: env("DATABASE_URL") //this is what specify the database connection string which is used by the PrismaClient to connect to our database and it will be loaded from the environment variables using the env function from the @prisma/config package and it will allow us to keep sensitive information such as database connection strings out of our source code and it will also allow us to easily manage different configurations for different environments such as development, testing, and production by using different .env files for each environment and it will also help us to avoid hardcoding sensitive information in our source code which can be a security risk if our code is ever exposed or leaked
  },
})